tag @s add start_game
tag @s remove desactive_event

tag @s remove wooden_sword
tag @s remove wooden_axe
tag @s remove wooden_pickaxe

tag @s remove loop_stopMove
tag @s remove desactive_event
tag @s remove desactive_lens
tag @s remove lens_active

tag @s remove only_level_armor
tag @s remove only_level_agility
tag @s remove only_level_mining
tag @s remove only_level_melee

tag @s remove stone_sword
tag @s remove stone_axe
tag @s remove stone_pickaxe

tag @s remove desactive_thirst
tag @s remove desactive_temp
tag @s remove doing_mining_wood

tag @s remove active_tuto0
tag @s remove active_tuto2
tag @s remove active_tuto3
tag @s remove active_tuto4
tag @s remove active_tuto5
tag @s remove active_tuto6
tag @s remove active_tuto7
tag @s remove active_tuto8
tag @s remove active_tuto9
tag @s remove active_tuto10
tag @s remove active_tuto11
tag @s remove active_tuto12
tag @s remove active_tuto13
tag @s remove active_tuto14
tag @s remove active_tuto15
tag @s remove active_tuto16
tag @s remove active_tuto17
tag @s remove active_tuto18
tag @s remove active_tuto19
tag @s remove active_tuto20
tag @s remove active_tuto21
tag @s remove active_tuto22
tag @s remove active_tuto23
tag @s remove active_tuto24
tag @s remove active_tuto25
tag @s remove active_tuto26
tag @s remove active_tuto26_2
tag @s remove active_tuto27
tag @s remove active_tuto28
tag @s remove active_tuto29
tag @s remove active_tuto30
tag @s remove active_tuto31

tag @s remove do_tuto0
tag @s remove do_tuto2
tag @s remove do_tuto3
tag @s remove do_tuto4
tag @s remove do_tuto5
tag @s remove do_tuto6
tag @s remove do_tuto7
tag @s remove do_tuto8
tag @s remove do_tuto9
tag @s remove do_tuto10
tag @s remove do_tuto11
tag @s remove do_tuto12
tag @s remove do_tuto13
tag @s remove do_tuto14
tag @s remove do_tuto15
tag @s remove do_tuto16
tag @s remove do_tuto17
tag @s remove do_tuto18
tag @s remove do_tuto19
tag @s remove do_tuto20
tag @s remove do_tuto21
tag @s remove do_tuto22
tag @s remove do_tuto23
tag @s remove do_tuto24
tag @s remove do_tuto25
tag @s remove do_tuto26_pre
tag @s remove do_tuto26
tag @s remove do_tuto27
tag @s remove do_tuto28
tag @s remove do_tuto29
tag @s remove do_tuto30
tag @s remove do_tuto31

tag @s remove active_do_tuto0
tag @s remove active_do_tuto2
tag @s remove active_do_tuto3
tag @s remove active_do_tuto4
tag @s remove active_do_tuto5
tag @s remove active_do_tuto6
tag @s remove active_do_tuto7
tag @s remove active_do_tuto8
tag @s remove active_do_tuto9
tag @s remove active_do_tuto10
tag @s remove active_do_tuto11
tag @s remove active_do_tuto12
tag @s remove active_do_tuto13
tag @s remove active_do_tuto14
tag @s remove active_do_tuto15
tag @s remove active_do_tuto16
tag @s remove active_do_tuto17
tag @s remove active_do_tuto18
tag @s remove active_do_tuto19
tag @s remove active_do_tuto20
tag @s remove active_do_tuto21
tag @s remove active_do_tuto21_2
tag @s remove active_do_tuto22
tag @s remove active_do_tuto23
tag @s remove active_do_tuto24
tag @s remove active_do_tuto25
tag @s remove active_do_tuto26
tag @s remove active_do_tuto27
tag @s remove active_do_tuto28
tag @s remove active_do_tuto29
tag @s remove active_do_tuto30
tag @s remove active_do_tuto31